const sfiaToRich = () => {
  return [
    "MLBR",
    "SBRN",
    "SSAN",
    "COLM",
    "DALY",
    "BALB",
    "GLEN",
    "24TH",
    "16TH",
    "CIVC",
    "POWL",
    "MONT",
    "EMBR",
    "WOAK",
    "12TH",
    "19TH",
    "MCAR",
    "ASHB",
    "DRBK",
    "NBRK",
    "PLZA",
    "DELN",
    "RICH",
  ];
  // abbr for SFO is SFIA
  // return {
  //   SFIA: [
  //     "MLBR",
  //     "SBRN",
  //     "SSAN",
  //     "COLM",
  //     "DALY",
  //     "BALB",
  //     "GLEN",
  //     "24TH",
  //     "16TH",
  //     "CIVC",
  //     "POWL",
  //     "MONT",
  //     "EMBR",
  //     "WOAK",
  //     "ASHB",
  //     "DRBK",
  //     "NBRK",
  //     "PLZA",
  //     "DELN",
  //     "RICH",
  //   ],
  //   MLBR: [
  //     "SBRN",
  //     "SSAN",
  //     "COLM",
  //     "DALY",
  //     "BALB",
  //     "GLEN",
  //     "24TH",
  //     "16TH",
  //     "CIVC",
  //     "POWL",
  //     "MONT",
  //     "EMBR",
  //     "WOAK",
  //     "ASHB",
  //     "DRBK",
  //     "NBRK",
  //     "PLZA",
  //     "DELN",
  //     "RICH",
  //   ],
  //   SBRN: [
  //     "SSAN",
  //     "COLM",
  //     "DALY",
  //     "BALB",
  //     "GLEN",
  //     "24TH",
  //     "16TH",
  //     "CIVC",
  //     "POWL",
  //     "MONT",
  //     "EMBR",
  //     "WOAK",
  //     "ASHB",
  //     "DRBK",
  //     "NBRK",
  //     "PLZA",
  //     "DELN",
  //     "RICH",
  //   ],
  //   SSAN: [
  //     "COLM",
  //     "DALY",
  //     "BALB",
  //     "GLEN",
  //     "24TH",
  //     "16TH",
  //     "CIVC",
  //     "POWL",
  //     "MONT",
  //     "EMBR",
  //     "WOAK",
  //     "ASHB",
  //     "DRBK",
  //     "NBRK",
  //     "PLZA",
  //     "DELN",
  //     "RICH",
  //   ],
  //   COLM: [
  //     "DALY",
  //     "BALB",
  //     "GLEN",
  //     "24TH",
  //     "16TH",
  //     "CIVC",
  //     "POWL",
  //     "MONT",
  //     "EMBR",
  //     "WOAK",
  //     "ASHB",
  //     "DRBK",
  //     "NBRK",
  //     "PLZA",
  //     "DELN",
  //     "RICH",
  //   ],
  //   DALY: [
  //     "BALB",
  //     "GLEN",
  //     "24TH",
  //     "16TH",
  //     "CIVC",
  //     "POWL",
  //     "MONT",
  //     "EMBR",
  //     "WOAK",
  //     "ASHB",
  //     "DRBK",
  //     "NBRK",
  //     "PLZA",
  //     "DELN",
  //     "RICH",
  //   ],
  //   BALB: [
  //     "GLEN",
  //     "24TH",
  //     "16TH",
  //     "CIVC",
  //     "POWL",
  //     "MONT",
  //     "EMBR",
  //     "WOAK",
  //     "ASHB",
  //     "DRBK",
  //     "NBRK",
  //     "PLZA",
  //     "DELN",
  //     "RICH",
  //   ],
  //   GLEN: [
  //     "24TH",
  //     "16TH",
  //     "CIVC",
  //     "POWL",
  //     "MONT",
  //     "EMBR",
  //     "WOAK",
  //     "ASHB",
  //     "DRBK",
  //     "NBRK",
  //     "PLZA",
  //     "DELN",
  //     "RICH",
  //   ],
  //   "24TH": [
  //     "16TH",
  //     "CIVC",
  //     "POWL",
  //     "MONT",
  //     "EMBR",
  //     "WOAK",
  //     "ASHB",
  //     "DRBK",
  //     "NBRK",
  //     "PLZA",
  //     "DELN",
  //     "RICH",
  //   ],
  //   "16TH": [
  //     "CIVC",
  //     "POWL",
  //     "MONT",
  //     "EMBR",
  //     "WOAK",
  //     "ASHB",
  //     "DRBK",
  //     "NBRK",
  //     "PLZA",
  //     "DELN",
  //     "RICH",
  //   ],
  //   CIVC: [
  //     "POWL",
  //     "MONT",
  //     "EMBR",
  //     "WOAK",
  //     "ASHB",
  //     "DRBK",
  //     "NBRK",
  //     "PLZA",
  //     "DELN",
  //     "RICH",
  //   ],
  //   POWL: [
  //     "MONT",
  //     "EMBR",
  //     "WOAK",
  //     "ASHB",
  //     "DRBK",
  //     "NBRK",
  //     "PLZA",
  //     "DELN",
  //     "RICH",
  //   ],
  //   MONT: ["EMBR", "WOAK", "ASHB", "DRBK", "NBRK", "PLZA", "DELN", "RICH"],
  //   EMBR: ["WOAK", "ASHB", "DRBK", "NBRK", "PLZA", "DELN", "RICH"],
  //   WOAK: ["ASHB", "DRBK", "NBRK", "PLZA", "DELN", "RICH"],
  //   ASHB: ["DRBK", "NBRK", "PLZA", "DELN", "RICH"],
  //   DRBK: ["NBRK", "PLZA", "DELN", "RICH"],
  //   NRBK: ["PLZA", "DELN", "RICH"],
  //   PLZA: ["DELN", "RICH"],
  //   DELN: "RICH"
  // };
};

export default sfiaToRich;
