const sfoToRich = () => {
  // abbr for SFO is SFIA
  return {
    SFIA: [
      "MLBR",
      "SBRN",
      "SSAN",
      "COLM",
      "DALY",
      "BALB",
      "GLEN",
      "24TH",
      "16TH",
      "CIVC",
      "POWL",
      "MONT",
      "EMBR",
      "WOAK",
      "ASHB",
      "DRBK",
      "NBRK",
      "PLZA",
      "DELN",
    ],
    MLBR: [
      "SBRN",
      "SSAN",
      "COLM",
      "DALY",
      "BALB",
      "GLEN",
      "24TH",
      "16TH",
      "CIVC",
      "POWL",
      "MONT",
      "EMBR",
      "WOAK",
      "ASHB",
      "DRBK",
      "NBRK",
      "PLZA",
      "DELN",
    ],
    SBRN: [
      "SSAN",
      "COLM",
      "DALY",
      "BALB",
      "GLEN",
      "24TH",
      "16TH",
      "CIVC",
      "POWL",
      "MONT",
      "EMBR",
      "WOAK",
      "ASHB",
      "DRBK",
      "NBRK",
      "PLZA",
      "DELN",
    ],
    SSAN: [
      "COLM",
      "DALY",
      "BALB",
      "GLEN",
      "24TH",
      "16TH",
      "CIVC",
      "POWL",
      "MONT",
      "EMBR",
      "WOAK",
      "ASHB",
      "DRBK",
      "NBRK",
      "PLZA",
      "DELN",
    ],
    COLM: [
      "DALY",
      "BALB",
      "GLEN",
      "24TH",
      "16TH",
      "CIVC",
      "POWL",
      "MONT",
      "EMBR",
      "WOAK",
      "ASHB",
      "DRBK",
      "NBRK",
      "PLZA",
      "DELN",
    ],
    DALY: [
      "BALB",
      "GLEN",
      "24TH",
      "16TH",
      "CIVC",
      "POWL",
      "MONT",
      "EMBR",
      "WOAK",
      "ASHB",
      "DRBK",
      "NBRK",
      "PLZA",
      "DELN",
    ],
    BALB: [
      "GLEN",
      "24TH",
      "16TH",
      "CIVC",
      "POWL",
      "MONT",
      "EMBR",
      "WOAK",
      "ASHB",
      "DRBK",
      "NBRK",
      "PLZA",
      "DELN",
    ],
    GLEN: [
      "24TH",
      "16TH",
      "CIVC",
      "POWL",
      "MONT",
      "EMBR",
      "WOAK",
      "ASHB",
      "DRBK",
      "NBRK",
      "PLZA",
      "DELN",
    ],
    "24TH": [
      "16TH",
      "CIVC",
      "POWL",
      "MONT",
      "EMBR",
      "WOAK",
      "ASHB",
      "DRBK",
      "NBRK",
      "PLZA",
      "DELN",
    ],
    "16TH": [
      "CIVC",
      "POWL",
      "MONT",
      "EMBR",
      "WOAK",
      "ASHB",
      "DRBK",
      "NBRK",
      "PLZA",
      "DELN",
    ],
    CIVC: [
      "POWL",
      "MONT",
      "EMBR",
      "WOAK",
      "ASHB",
      "DRBK",
      "NBRK",
      "PLZA",
      "DELN",
    ],
    POWL: ["MONT", "EMBR", "WOAK", "ASHB", "DRBK", "NBRK", "PLZA", "DELN"],
    MONT: ["EMBR", "WOAK", "ASHB", "DRBK", "NBRK", "PLZA", "DELN"],
    EMBR: ["WOAK", "ASHB", "DRBK", "NBRK", "PLZA", "DELN"],
    WOAK: ["ASHB", "DRBK", "NBRK", "PLZA", "DELN"],
    ASHB: ["DRBK", "NBRK", "PLZA", "DELN"],
    DRBK: ["NBRK", "PLZA", "DELN"],
    NRBK: ["PLZA", "DELN"],
    PLZA: ["DELN"],
  };
};

export default sfoToRich;
